---
title: "Fleet Science Center - Google Analytics metrics"
author: "Diego Enriquez"
date: "29/9/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE, warning=FALSE}
suppressMessages(library(data.table))
suppressMessages(library(lubridate))
suppressMessages(library(ggplot2))
suppressMessages(library(grid))

# Functions ==================================================================================================================================
source("fleet_func.R")
```

```{r echo=FALSE, warning=FALSE}
ga_allws_nochn_all <- readQueryExplorerData("data/ga/fleet_allws_nochn_all.tsv", c("Date"))
ga_allws_nochn_os <- readQueryExplorerData("data/ga/fleet_allws_nochn_os.tsv", c("Date"))
ga_allws_nochn_us <- readQueryExplorerData("data/ga/fleet_allws_nochn_us.tsv", c("Date"))
ga_allws_nochn_do <- readQueryExplorerData("data/ga/fleet_allws_nochn_do.tsv", c("Date"))
ga_allws_nochn_lo <- readQueryExplorerData("data/ga/fleet_allws_nochn_lo.tsv", c("Date"))

ga_allws_chn_all <- readQueryExplorerData("data/ga/fleet_allws_chn_all.tsv", c("Date", "Channel"))
ga_allws_chn_os <- readQueryExplorerData("data/ga/fleet_allws_chn_os.tsv", c("Date", "Channel"))
ga_allws_chn_us <- readQueryExplorerData("data/ga/fleet_allws_chn_us.tsv", c("Date", "Channel"))
ga_allws_chn_do <- readQueryExplorerData("data/ga/fleet_allws_chn_do.tsv", c("Date", "Channel"))
ga_allws_chn_lo <- readQueryExplorerData("data/ga/fleet_allws_chn_lo.tsv", c("Date", "Channel"))

ga_admin_nochn_all <- readQueryExplorerData("data/ga/fleet_admin_nochn_all.tsv", c("Date"))
ga_admin_nochn_os <- readQueryExplorerData("data/ga/fleet_admin_nochn_os.tsv", c("Date"))
ga_admin_nochn_us <- readQueryExplorerData("data/ga/fleet_admin_nochn_us.tsv", c("Date"))
ga_admin_nochn_do <- readQueryExplorerData("data/ga/fleet_admin_nochn_do.tsv", c("Date"))
ga_admin_nochn_lo <- readQueryExplorerData("data/ga/fleet_admin_nochn_lo.tsv", c("Date"))

ga_admin_chn_all <- readQueryExplorerData("data/ga/fleet_admin_chn_all.tsv", c("Date", "Channel"))
ga_admin_chn_os <- readQueryExplorerData("data/ga/fleet_admin_chn_os.tsv", c("Date", "Channel"))
ga_admin_chn_us <- readQueryExplorerData("data/ga/fleet_admin_chn_us.tsv", c("Date", "Channel"))
ga_admin_chn_do <- readQueryExplorerData("data/ga/fleet_admin_chn_do.tsv", c("Date", "Channel"))
ga_admin_chn_lo <- readQueryExplorerData("data/ga/fleet_admin_chn_lo.tsv", c("Date", "Channel"))

ga_shows_nochn_all <- readQueryExplorerData("data/ga/fleet_shows_nochn_all.tsv", c("Date"))
ga_shows_nochn_os <- readQueryExplorerData("data/ga/fleet_shows_nochn_os.tsv", c("Date"))
ga_shows_nochn_us <- readQueryExplorerData("data/ga/fleet_shows_nochn_us.tsv", c("Date"))
ga_shows_nochn_do <- readQueryExplorerData("data/ga/fleet_shows_nochn_do.tsv", c("Date"))
ga_shows_nochn_lo <- readQueryExplorerData("data/ga/fleet_shows_nochn_lo.tsv", c("Date"))

ga_shows_chn_all <- readQueryExplorerData("data/ga/fleet_shows_chn_all.tsv", c("Date", "Channel"))
ga_shows_chn_os <- readQueryExplorerData("data/ga/fleet_shows_chn_os.tsv", c("Date", "Channel"))
ga_shows_chn_us <- readQueryExplorerData("data/ga/fleet_shows_chn_us.tsv", c("Date", "Channel"))
ga_shows_chn_do <- readQueryExplorerData("data/ga/fleet_shows_chn_do.tsv", c("Date", "Channel"))
ga_shows_chn_lo <- readQueryExplorerData("data/ga/fleet_shows_chn_lo.tsv", c("Date", "Channel"))

ga_exhib_nochn_all <- readQueryExplorerData("data/ga/fleet_exhib_nochn_all.tsv", c("Date"))
ga_exhib_nochn_os <- readQueryExplorerData("data/ga/fleet_exhib_nochn_os.tsv", c("Date"))
ga_exhib_nochn_us <- readQueryExplorerData("data/ga/fleet_exhib_nochn_us.tsv", c("Date"))
ga_exhib_nochn_do <- readQueryExplorerData("data/ga/fleet_exhib_nochn_do.tsv", c("Date"))
ga_exhib_nochn_lo <- readQueryExplorerData("data/ga/fleet_exhib_nochn_lo.tsv", c("Date"))

ga_exhib_chn_all <- readQueryExplorerData("data/ga/fleet_exhib_chn_all.tsv", c("Date", "Channel"))
ga_exhib_chn_os <- readQueryExplorerData("data/ga/fleet_exhib_chn_os.tsv", c("Date", "Channel"))
ga_exhib_chn_us <- readQueryExplorerData("data/ga/fleet_exhib_chn_us.tsv", c("Date", "Channel"))
ga_exhib_chn_do <- readQueryExplorerData("data/ga/fleet_exhib_chn_do.tsv", c("Date", "Channel"))
ga_exhib_chn_lo <- readQueryExplorerData("data/ga/fleet_exhib_chn_lo.tsv", c("Date", "Channel"))

ga_exhib2_nochn_all <- readQueryExplorerData("data/ga/fleet_exhib2_nochn_all.tsv", c("Date"))
ga_exhib2_nochn_os <- readQueryExplorerData("data/ga/fleet_exhib2_nochn_os.tsv", c("Date"))
ga_exhib2_nochn_us <- readQueryExplorerData("data/ga/fleet_exhib2_nochn_us.tsv", c("Date"))
ga_exhib2_nochn_do <- readQueryExplorerData("data/ga/fleet_exhib2_nochn_do.tsv", c("Date"))
ga_exhib2_nochn_lo <- readQueryExplorerData("data/ga/fleet_exhib2_nochn_lo.tsv", c("Date"))

ga_exhib2_chn_all <- readQueryExplorerData("data/ga/fleet_exhib2_chn_all.tsv", c("Date", "Channel"))
ga_exhib2_chn_os <- readQueryExplorerData("data/ga/fleet_exhib2_chn_os.tsv", c("Date", "Channel"))
ga_exhib2_chn_us <- readQueryExplorerData("data/ga/fleet_exhib2_chn_us.tsv", c("Date", "Channel"))
ga_exhib2_chn_do <- readQueryExplorerData("data/ga/fleet_exhib2_chn_do.tsv", c("Date", "Channel"))
ga_exhib2_chn_lo <- readQueryExplorerData("data/ga/fleet_exhib2_chn_lo.tsv", c("Date", "Channel"))

daysinfo <- data.table(Date = seq(as.Date("2017-07-01"), as.Date("2018-07-12"), by = "day"))
daysinfo$weekNum <- wday(daysinfo$Date, week_start = 1)
daysinfo$isFirstSunday <- wday(daysinfo$Date, week_start = 1) == 7 & day(daysinfo$Date) <= 7
```

## All Web Site

### All locations

```{r ga_allws_nochn_all, echo=FALSE, fig.width=10}
gadata <- completeGADates(ga_allws_nochn_all, limitDates = c("2017-07-01", "2018-07-12"))  # or,
plotsGA <- getPlotGAList(gadata)

grid.newpage(); grid.draw(rbind(ggplotGrob(plotsGA[[1]]), ggplotGrob(plotsGA[[2]]), ggplotGrob(plotsGA[[3]]), size = "last"))
grid.newpage(); grid.draw(rbind(ggplotGrob(plotsGA[[4]]), ggplotGrob(plotsGA[[5]]), ggplotGrob(plotsGA[[6]]), size = "last"))
grid.newpage(); grid.draw(rbind(ggplotGrob(plotsGA[[7]]), ggplotGrob(plotsGA[[8]]), ggplotGrob(plotsGA[[9]]), size = "last"))
grid.newpage(); grid.draw(rbind(ggplotGrob(plotsGA[[10]]), ggplotGrob(plotsGA[[11]]), ggplotGrob(plotsGA[[12]]), size = "last"))
```

### Overseas

```{r ga_allws_nochn_os, echo=FALSE, fig.width=10}
gadata <- completeGADates(ga_allws_nochn_os, limitDates = c("2017-07-01", "2018-07-12"))  # or,
plotsGA <- getPlotGAList(gadata)

grid.newpage(); grid.draw(rbind(ggplotGrob(plotsGA[[1]]), ggplotGrob(plotsGA[[2]]), ggplotGrob(plotsGA[[3]]), size = "last"))
grid.newpage(); grid.draw(rbind(ggplotGrob(plotsGA[[4]]), ggplotGrob(plotsGA[[5]]), ggplotGrob(plotsGA[[6]]), size = "last"))
grid.newpage(); grid.draw(rbind(ggplotGrob(plotsGA[[7]]), ggplotGrob(plotsGA[[8]]), ggplotGrob(plotsGA[[9]]), size = "last"))
grid.newpage(); grid.draw(rbind(ggplotGrob(plotsGA[[10]]), ggplotGrob(plotsGA[[11]]), ggplotGrob(plotsGA[[12]]), size = "last"))
```

### United States

```{r ga_allws_nochn_us, echo=FALSE, fig.width=10}
gadata <- completeGADates(ga_allws_nochn_us, limitDates = c("2017-07-01", "2018-07-12"))  # or,
plotsGA <- getPlotGAList(gadata)

grid.newpage(); grid.draw(rbind(ggplotGrob(plotsGA[[1]]), ggplotGrob(plotsGA[[2]]), ggplotGrob(plotsGA[[3]]), size = "last"))
grid.newpage(); grid.draw(rbind(ggplotGrob(plotsGA[[4]]), ggplotGrob(plotsGA[[5]]), ggplotGrob(plotsGA[[6]]), size = "last"))
grid.newpage(); grid.draw(rbind(ggplotGrob(plotsGA[[7]]), ggplotGrob(plotsGA[[8]]), ggplotGrob(plotsGA[[9]]), size = "last"))
grid.newpage(); grid.draw(rbind(ggplotGrob(plotsGA[[10]]), ggplotGrob(plotsGA[[11]]), ggplotGrob(plotsGA[[12]]), size = "last"))
```

### Domestics

```{r ga_allws_nochn_do, echo=FALSE, fig.width=10}
gadata <- completeGADates(ga_allws_nochn_do, limitDates = c("2017-07-01", "2018-07-12"))  # or,
plotsGA <- getPlotGAList(gadata)

grid.newpage(); grid.draw(rbind(ggplotGrob(plotsGA[[1]]), ggplotGrob(plotsGA[[2]]), ggplotGrob(plotsGA[[3]]), size = "last"))
grid.newpage(); grid.draw(rbind(ggplotGrob(plotsGA[[4]]), ggplotGrob(plotsGA[[5]]), ggplotGrob(plotsGA[[6]]), size = "last"))
grid.newpage(); grid.draw(rbind(ggplotGrob(plotsGA[[7]]), ggplotGrob(plotsGA[[8]]), ggplotGrob(plotsGA[[9]]), size = "last"))
grid.newpage(); grid.draw(rbind(ggplotGrob(plotsGA[[10]]), ggplotGrob(plotsGA[[11]]), ggplotGrob(plotsGA[[12]]), size = "last"))
```

### Locals

```{r ga_allws_nochn_lo, echo=FALSE, fig.width=10}
gadata <- completeGADates(ga_allws_nochn_lo, limitDates = c("2017-07-01", "2018-07-12"))  # or,
plotsGA <- getPlotGAList(gadata)

grid.newpage(); grid.draw(rbind(ggplotGrob(plotsGA[[1]]), ggplotGrob(plotsGA[[2]]), ggplotGrob(plotsGA[[3]]), size = "last"))
grid.newpage(); grid.draw(rbind(ggplotGrob(plotsGA[[4]]), ggplotGrob(plotsGA[[5]]), ggplotGrob(plotsGA[[6]]), size = "last"))
grid.newpage(); grid.draw(rbind(ggplotGrob(plotsGA[[7]]), ggplotGrob(plotsGA[[8]]), ggplotGrob(plotsGA[[9]]), size = "last"))
grid.newpage(); grid.draw(rbind(ggplotGrob(plotsGA[[10]]), ggplotGrob(plotsGA[[11]]), ggplotGrob(plotsGA[[12]]), size = "last"))
```

### Channels

```{r ga_allws_chn_all, echo=FALSE, fig.width=10}
gadata <- completeGADates(ga_allws_chn_all[Channel == "Organic Search"], limitDates = c("2017-07-01", "2018-07-12"))
plotsGA <- getPlotGAList(gadata)

grid.newpage(); grid.draw(rbind(ggplotGrob(plotsGA[[1]]), ggplotGrob(plotsGA[[2]]), ggplotGrob(plotsGA[[3]]), size = "last"))
grid.newpage(); grid.draw(rbind(ggplotGrob(plotsGA[[4]]), ggplotGrob(plotsGA[[5]]), ggplotGrob(plotsGA[[6]]), size = "last"))
grid.newpage(); grid.draw(rbind(ggplotGrob(plotsGA[[7]]), ggplotGrob(plotsGA[[8]]), ggplotGrob(plotsGA[[9]]), size = "last"))
grid.newpage(); grid.draw(rbind(ggplotGrob(plotsGA[[10]]), ggplotGrob(plotsGA[[11]]), ggplotGrob(plotsGA[[12]]), size = "last"))
```
